[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=69.0.2",
    "setuptools-scm>=8.0.4",
]

[project]
name = "cooper-optim"
description = "cooper is a toolkit for Lagrangian-based constrained optimization in PyTorch"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT License" }
maintainers = [
    { name = "Jose Gallego-Posada", email = "jgalle29@gmail.com" },
    { name = "Juan Ramirez", email = "juan43.ramirez@gmail.com" },
    { name = "Meraj Hashemizadeh", email = "merajhashemi@yahoo.co.uk" },
]
authors = [
    { name = "Jose Gallego-Posada", email = "jgalle29@gmail.com" },
    { name = "Juan Ramirez", email = "juan43.ramirez@gmail.com" },
    { name = "Meraj Hashemizadeh", email = "merajhashemi@yahoo.co.uk" },
]
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dynamic = [ "version" ]
dependencies = [
    "numpy>=1.22.0,<2.0.0", # PyTorch 2.2.2 and older don't support NumPy 2.0.
    "torch>=1.13.1",
    "typing-extensions>=4.8.0",
]

[project.optional-dependencies]
dev = [
    "cvxpy~=1.5.1",
    "mypy~=1.7.1",
    "pre-commit>=3.6.0",
    "pytest~=8.2.2",
    "pytest-cov==4.1.0",
    "ruff~=0.5.5",
    "tox==4.11.4",
    "twine==4.0.2",
]
docs = [
    "ipykernel>=6.5.0,<7.0.0",
    "ipywidgets>=7.6.0,<8.0.0",
    "jupytext>=1.16.3",
    "matplotlib>=3.5.0,<4.0.0",
    "myst-nb>=1.1.1",
    "sphinx>=4.3.1",
    "sphinx-autobuild>=2021.3.14",
    "sphinx-autodoc-typehints>=1.12.0",
    "sphinx-copybutton>=0.4.0",
    "sphinx-rtd-theme>=1.0.0",
    "sphinxcontrib-bibtex>=2.4.1",
    "sphinxcontrib-contentui>=0.2.5",
    "sphinxcontrib-katex>=0.8.6",
    "torchvision>=0.13.0,<1.0.0",
]
examples = [
    "ipykernel>=6.5.0,<7.0.0",
    "ipywidgets>=7.6.0,<8.0.0",
    "matplotlib>=3.5.0,<4.0.0",
    "numpy==1.22.0",
    "torchvision>=0.13.0,<1.0.0",
]
tests = [
    "cvxpy~=1.5.1",
    "pytest~=8.2.2",
    "pytest-cov==4.1.0",
    "tox==4.11.4",
]

[project.urls]
Homepage = "https://github.com/cooper-org/cooper"
Documentation = "https://cooper.readthedocs.io"
Repository = "https://github.com/cooper-org/cooper"
Issues = "https://github.com/cooper-org/cooper/issues"

[tool.setuptools]
license-files = ["LICENSE"]

[tool.setuptools.package-data]
cooper = ["py.typed"]

[tool.setuptools_scm]

[tool.mypy]
mypy_path = "cooper"
warn_unused_configs = true

[tool.ruff]
line-length = 120
target-version = "py39"
extend-include = ["*.ipynb"]

[tool.ruff.lint.isort]
known-first-party = ["cooper", "tests"]

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
    "B028",     # Stacklevel in warnings
    "E501",     # Line length (handled by ruff-format)
    "E731",     # Lambda function
    "W505",     # Doc Line length
    "D1",       # TODO: Uncomment this line when we have docstrings for all functions
    "D205",     # 1 blank line required between summary line and description in docstrings
    "DOC501",   # Docstring missing exceptions
    "ISC001",   # Fixed by ruff-format
    "COM812",   # Fixed by ruff-format
    "FA",       # Future type annotations
    "CPY",      # Copyright notice
    "TRY003",   # Long Exception message
    "SLF",      # Private (underscore) attribute access
    "EM",       # Exception message not in seperate msg variable
    "PLR09",    # Too many arguments
    "PLR2004",  # Use of value instead of constant variable
    "PLR6104",  # Forces in-place operations, for example, x += 1 instead of x = x + 1
    "PLR6301",  # Self not used in method
    "PLW2901",  # For loop variable is overwritten
    "FBT",      # Boolean trap
    "FIX",      # Fixmes
    "TD",       # TODOs
    "ANN401",   # Any type annotation
    "PTH",      # Use Pathlib instead of os.path
    "FURB140",  # Use itertools.starmap instead of list comprehension
    "NPY002",   # numpy.random.Generator is preferred over numpy.random.seed
    "RET504",   # Unnecessary assignment before return
    "S101",     # Use of assert
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["ANN", "C901", "N801", "N802", "N803", "N806"]
"docs/*" = ["ANN"]
"docs/source/conf.py" = ["A001", "ERA001", "INP001"]
"docs/source/notebooks/*" = ["N801", "N802", "N803", "N806"]
"src/cooper/optim/torch_optimizers/nupi_optimizer.py" = ["C901", "N801", "N802", "N803", "N806"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pycodestyle]
max-doc-length = 88
