[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools-scm>=8.0.4",
    "setuptools>=69.0.2",
    "wheel>=0.42.0",
]

[tool.setuptools_scm]
write_to = "cooper/version.py"

[tool.mypy]
mypy_path = "cooper"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
