name: Coverage

on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]

jobs:
    build:
        runs-on: ubuntu-latest

        # Setup lastest python version
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install codecov pytest-cov
                  pip install .[dev]
            - name: Coverage tests
              run: pytest --cov=cooper . --cov-report term-missing

            - name: Codecov
              if: success()
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: codecov
