name: Publish package

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v.**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build package
        id: build
        run: python -m build

      - name: Upload package to PyPI
        id: pypi
        if: steps.build.outcome == 'success'
        uses: pypa/gh-action-pypi-publish@v1.9
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish release to GitHub
        if: steps.build.pypi == 'success'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish documentation
        if: steps.build.pypi == 'success'
        run: echo "TODO"  # TODO: Build docs and push to readthedocs.io
