name: Publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create GitHub releases
      id-token: write  # Required for trusted PyPI publishing via OIDC
    steps:
      - name:  Checkout Repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Build Package
        id: build
        run: uv build

      - name: Publish to PyPI
        id: pypi
        if: steps.build.outcome == 'success'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true

      - name: Create GitHub Release
        if: steps.pypi.outcome == 'success'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
