name: Publish package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for making GitHub releases
      id-token: write  # Needed for trusted publishing to PyPI
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Build package
        id: build
        run: uv build

      - name: Publish package to PyPI
        id: pypi
        if: steps.build.outcome == 'success'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true

      - name: Publish release to GitHub
        if: steps.pypi.outcome == 'success'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
